import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#ECE7E3", paddingHorizontal: 16 },
  title: {
    fontSize: 32,
    fontWeight: "900",
    marginTop: 12,
    marginBottom: 24,
    color: "#3F1C0A",
  },
  form: { flex: 1, justifyContent: "space-between" },
  field: { marginBottom: 20 },
  label: { fontSize: 16, fontWeight: "600", marginBottom: 8, color: "#38137d" },
  input: {
    height: 50,
    minWidth: 200,
    borderWidth: 1,
    borderColor: "#5E3D9B",
    borderRadius: 8,
    paddingHorizontal: 15,
    fontSize: 16,
    backgroundColor: "#fafafa",
    //hard shadow styling
    shadowColor: "#000",
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    boxShadow: "4px 4px 0px 0px #38137d",
  },
  pickerWrapper: {
    overflow: "hidden",
    justifyContent: "center",
    height: 50,
    minWidth: 200,
    borderWidth: 1,
    borderColor: "#5E3D9B",
    borderRadius: 8,
    // paddingHorizontal: 15,
    fontSize: 16,
    backgroundColor: "#fafafa",
    //hard shadow styling
    shadowColor: "#000",
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    boxShadow: "4px 4px 0px 0px #38137d",
  },
  errorText: { color: "#DC2626", fontSize: 12, marginTop: 4 },
  hostButton: {
    backgroundColor: "#38137D",
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: "center",
    marginBottom: 16,
    //hard shadow styling
    shadowColor: "#5E3D9B",
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    boxShadow: "4px 4px 0px 0px #5E3D9B",
  },
  hostButtonDisabled: { opacity: 0.5 },
  hostButtonText: { color: "#ECE7E3", fontWeight: "700", fontSize: 16 },
});
